### ISSUE TITLE
google-analytics-pluginを組み入れるとAndroidでビルドエラーとなる。

### ISSUE THREAD

**Issue by mogamin** [NIFTYCloud-mbaas/monaca_push_plugin#22]
## 不具合の概要(Description of bug)
ncmb-push-monaca-plugin と https://github.com/cmackay/google-analytics-plugin.gitをあわせてビルドするとコンパイルエラー（com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/iid/MessengerCompat$1）となる。
https://github.com/danwilson/google-analytics-pluginでも同じ現象が発生する。

- SDKのバージョン(SDK version)
2.0.3,2.0.4

- 不具合が発生した環境(Environment requirement)
Androidのビルド

- エラーメッセージ(Error messages)
```
Fetch queue Info...
Start building 589b165eff2af2bb145c218f
Setup working directories...
Download project archive...
Extract project archive...
Fetch project info...
Webview:null
Arch:null
cordova version: 6.2.0


- preBuild -
buildForAndroid

- Cordova create -
$ /data/build-server/cordova/6.2.0/bin/cordova create /tmp/monaca/589b165eff2af2bb145c218f/project
Creating a new cordova project.


- Copy .monaca-res directory -

- Cordova platform add -
$ /data/build-server/cordova/6.2.0/bin/cordova platform list
$ /data/build-server/cordova/6.2.0/bin/cordova platform add /data/build-server/cordova/platforms/android/5.1.1
Adding android project...
Creating Cordova project for the Android platform:
	Path: platforms/android
	Package: io.cordova.hellocordova
	Name: HelloCordova
	Activity: MainActivity
	Android target: android-23
Android project created with cordova-android@5.1.1
Discovered plugin "cordova-plugin-whitelist" in config.xml. Adding it to the project
Fetching plugin "cordova-plugin-whitelist@1" via npm
Installing "cordova-plugin-whitelist" for android

               This plugin is only applicable for versions of cordova-android greater than 4.0. If you have a previous platform version, you do *not* need this plugin since the whitelist will be built in.
          


- Copy config.xml -

- Copy files for signing -

- Copy www files -

- Cordova plugin add -
$ /data/build-server/cordova/6.2.0/bin/cordova plugin add mobi.monaca.plugins.Monaca
$ /data/build-server/cordova/6.2.0/bin/cordova plugin add mobi.monaca.plugins.WebIntent@1.0.0
$ /data/build-server/cordova/6.2.0/bin/cordova plugin add cordova-plugin-statusbar@2.1.3
$ /data/build-server/cordova/6.2.0/bin/cordova plugin add cordova-custom-config@2.0.3
$ /data/build-server/cordova/6.2.0/bin/cordova plugin add cordova-plugin-whitelist@1.2.2
$ /data/build-server/cordova/6.2.0/bin/cordova plugin add cordova-plugin-splashscreen@4.0.1
$ /data/build-server/cordova/6.2.0/bin/cordova plugin add cordova-plugin-inappbrowser@1.5.0
$ /data/build-server/cordova/6.2.0/bin/cordova plugin add ncmb-push-monaca-plugin@2.0.4
$ /data/build-server/cordova/6.2.0/bin/cordova plugin add https://github.com/cmackay/google-analytics-plugin.git#v1.0.2
$ /data/build-server/cordova/6.2.0/bin/cordova plugin add https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin.git#5.1.3

- Cordova prepare -
$ /data/build-server/cordova/6.2.0/bin/cordova prepare android
cordova-custom-config: Skipping auto-restore of config file backup(s)


- Cordova compile -
$ /data/build-server/cordova/6.2.0/bin/cordova compile --release --device
ANDROID_HOME=/data/android-sdk
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_111.jdk/Contents/Home
:preBuild UP-TO-DATE
:preReleaseBuild UP-TO-DATE
:checkReleaseManifest
:CordovaLib:preBuild UP-TO-DATE
:CordovaLib:preReleaseBuild UP-TO-DATE
:CordovaLib:compileReleaseNdk UP-TO-DATE
:CordovaLib:compileLint
:CordovaLib:copyReleaseLint UP-TO-DATE
:CordovaLib:mergeReleaseProguardFiles
:CordovaLib:packageReleaseRenderscript UP-TO-DATE
:CordovaLib:checkReleaseManifest
:CordovaLib:prepareReleaseDependencies
:CordovaLib:compileReleaseRenderscript
:CordovaLib:generateReleaseResValues
:CordovaLib:generateReleaseResources
:CordovaLib:packageReleaseResources
:CordovaLib:compileReleaseAidl
:CordovaLib:generateReleaseBuildConfig
:CordovaLib:generateReleaseAssets UP-TO-DATE
:CordovaLib:mergeReleaseAssets
:CordovaLib:processReleaseManifest
:CordovaLib:processReleaseResources
:CordovaLib:generateReleaseSources
:CordovaLib:compileReleaseJavaWithJavac
:CordovaLib:processReleaseJavaRes UP-TO-DATE
:CordovaLib:transformResourcesWithMergeJavaResForRelease
:CordovaLib:transformClassesAndResourcesWithSyncLibJarsForRelease
:CordovaLib:mergeReleaseJniLibFolders
:CordovaLib:transformNative_libsWithMergeJniLibsForRelease
:CordovaLib:transformNative_libsWithSyncJniLibsForRelease
:CordovaLib:bundleRelease
:prepareAndroidCordovaLibUnspecifiedReleaseLibrary
:preDebugBuild UP-TO-DATE
:CordovaLib:preDebugBuild UP-TO-DATE
:CordovaLib:compileDebugNdk UP-TO-DATE
:CordovaLib:copyDebugLint UP-TO-DATE
:CordovaLib:mergeDebugProguardFiles
:CordovaLib:packageDebugRenderscript UP-TO-DATE
:CordovaLib:checkDebugManifest
:CordovaLib:prepareDebugDependencies
:CordovaLib:compileDebugRenderscript
:CordovaLib:generateDebugResValues
:CordovaLib:generateDebugResources
:CordovaLib:packageDebugResources
:CordovaLib:compileDebugAidl
:CordovaLib:generateDebugBuildConfig
:CordovaLib:generateDebugAssets UP-TO-DATE
:CordovaLib:mergeDebugAssets
:CordovaLib:processDebugManifest
:CordovaLib:processDebugResources
:CordovaLib:generateDebugSources
:CordovaLib:compileDebugJavaWithJavac
:CordovaLib:processDebugJavaRes UP-TO-DATE
:CordovaLib:transformResourcesWithMergeJavaResForDebug
:CordovaLib:transformClassesAndResourcesWithSyncLibJarsForDebug
:CordovaLib:mergeDebugJniLibFolders
:CordovaLib:transformNative_libsWithMergeJniLibsForDebug
:CordovaLib:transformNative_libsWithSyncJniLibsForDebug
:CordovaLib:bundleDebug
:prepareComAndroidSupportSupportV42221Library
:prepareComGoogleAndroidGmsPlayServicesAnalytics1000Library
:prepareComGoogleAndroidGmsPlayServicesAnalyticsImpl1000Library
:prepareComGoogleAndroidGmsPlayServicesBase1000Library
:prepareComGoogleAndroidGmsPlayServicesBasement1000Library
:prepareComGoogleAndroidGmsPlayServicesGcm810Library
:prepareComGoogleAndroidGmsPlayServicesTagmanagerV4Impl1000Library
:prepareComGoogleAndroidGmsPlayServicesTasks1000Library
:prepareReleaseDependencies
:compileReleaseAidl
:compileReleaseRenderscript
:generateReleaseBuildConfig
:generateReleaseAssets UP-TO-DATE
:mergeReleaseAssets
:generateReleaseResValues
:generateReleaseResources
:mergeReleaseResources
:processReleaseManifest
:processReleaseResources
:generateReleaseSources
:compileReleaseJavaWithJavac
:compileReleaseNdk UP-TO-DATE
:compileReleaseSources
:lintVitalRelease
:transformClassesWithDexForRelease FAILED

BUILD FAILED

Total time: 29.114 secs


- postBuild -
Remove working directories...
Build Error: Error: Sandbox Exec Error: [ 注意:一部の入力ファイルは非推奨のAPIを使用またはオーバーライドしています。
注意:詳細は、-Xlint:deprecationオプションを指定して再コンパイルしてください。
注意:一部の入力ファイルは非推奨のAPIを使用またはオーバーライドしています。
注意:詳細は、-Xlint:deprecationオプションを指定して再コンパイルしてください。
注意:一部の入力ファイルは非推奨のAPIを使用またはオーバーライドしています。
注意:詳細は、-Xlint:deprecationオプションを指定して再コンパイルしてください。

UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/iid/MessengerCompat$1;
	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:579)
	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:535)
	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:517)
	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:164)
	at com.android.dx.merge.DexMerger.merge(DexMerger.java:188)
	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:504)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
	at com.android.dx.command.dexer.Main.run(Main.java:277)
	at com.android.dx.command.dexer.Main.main(Main.java:245)
	at com.android.dx.command.Main.main(Main.java:106)



FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformClassesWithDexForRelease'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_111.jdk/Contents/Home/bin/java'' finished with non-zero exit value 2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Error: Error code 1 for command: /private/tmp/monaca/589b165eff2af2bb145c218f/project/platforms/android/gradlew with args: cdvBuildRelease,-b,/private/tmp/monaca/589b165eff2af2bb145c218f/project/platforms/android/build.gradle,-Dorg.gradle.daemon=true,-Pandroid.useDeprecatedNdk=true
 ]
```

**Comment by mogamin** [comment]
https://github.com/danwilson/google-analytics-plugin をforkし、NCMBで利用しているgoogle-play-service-core8.1.0のバージョンに修正して、それを組み入れることで解決した。
